# Load the necessary libraries
library(glue)
library(yaml)
library(tidyverse)

# Read the YAML file
yaml_data = yaml::read_yaml("packing/data.yaml")

# Function to convert YAML to roxygen
convert_yaml_to_roxygen = function(yaml_data, dataset_name) {
	# Read the template from a file
	roxygen_template = read_file("packing/data.roxogen.template")

	# Replace "\n" with "\n#' " in all values
	yaml_data =  map(
		yaml_data,
		~{
			if(!is.list(.x)) str_replace_all(str_trim(.x), "\n", "\n#' ")
			else .x
		}
	)

	# Extract variables and format them
	variables = yaml_data$describe|>
		map_chr(function(x){
			d = str_replace_all(x[3], "\n", "\n#'\t")
			glue(
				"#'\t\\item{<x[1]>}{`<x[2]>` <d>}",
				.open = "<",
				.close = ">"
			)
		})

	# Add formatted variables to yaml_data
	yaml_data$variables = str_trim(paste(variables, collapse = "\n"))

	yaml_data$dataset_name = dataset_name

	# Concatenate all values into a single string
	yaml_data = map(yaml_data, ~str_trim(paste(.x, collapse = "\n")))

	if(!"examples" %in% names(yaml_data))yaml_data$examples = glue("data({dataset_name})")
	yaml_data$examples = paste("#'", str_trim(yaml_data$examples))

	# Use glue to fill in the template
	roxygen = glue_data(yaml_data, roxygen_template, .sep = "")

	return(roxygen)
}


# Use purrr's map function to convert the YAML to roxygen
roxygen_list = yaml_data|>
	purrr::imap(convert_yaml_to_roxygen)|>
	unlist()|>
	paste(collapse = '')

# Write the roxygen documentation to a file
write_file(glue("# Generated by packing/gen_roxogen.R\n# Do not edit by hand, instead edit packing/data.yaml\n{roxygen_list}"), "R/data.R")
