# Generated by packing/gen_roxogen.R
# Do not edit by hand, instead edit packing/data.yaml
#' National PokeDex
#'
#' The National PokeDex is a comprehensive database that records information on all Pokémon known to exist,
#' instead of just ones native in a particular region.
#' This dataset provides information about Pokémon as per the National Pokédex,
#' which includes Pokémon from the Kanto region first, followed by those from Johto,
#' Hoenn, Sinnoh, Unova, Kalos, Alola, Galar, Hisui, and Paldea.
#' @format A data frame with 12 variables:
#' \describe{
#'	\item{`ndex`}{`integer` National Pokedex number. This is the unique identifier for each Pokémon in the National Pokédex.}
#'	\item{`name`}{`character` Name of the Pokemon. This is the common name used to identify a particular Pokémon.}
#'	\item{`form`}{`character` Form of the Pokemon. This refers to the different physical forms that Pokémon can take. NA if the Pokemon does not have a special form.}
#'	\item{`regional`}{`character` Regional form of the Pokemon. This refers to the variations of Pokémon that appear differently and have different attributes compared to their counterparts in other regions. NA if the Pokemon does not have a regional form.}
#'	\item{`type`}{`character` Primary type of the Pokemon. This is the main elemental category the Pokémon belongs to, such as Water, Fire, Grass, etc.}
#'	\item{`type2`}{`character` Secondary type of the Pokemon. This is the secondary elemental category the Pokémon belongs to, if any. NA if the Pokemon does not have a secondary type.}
#'	\item{`generation`}{`integer` The generation the Pokemon was introduced in. This refers to the different stages of Pokémon games, each introducing new Pokémon, regions, and gameplay concepts.}
#'	\item{`isLegendary`}{`logical` Whether the Pokemon is Legendary. This indicates if the Pokémon is a Legendary Pokémon, which are a group of incredibly rare and often very powerful Pokémon.}
#'	\item{`isMythical`}{`logical` Whether the Pokemon is Mythical. This indicates if the Pokémon is a Mythical Pokémon, which are a group of Pokémon seen so rarely in the Pokémon world that some question their very existence.}
#'	\item{`isUltraBeast`}{`logical` Whether the Pokemon is an Ultra Beast. This indicates if the Pokémon is an Ultra Beast, which are a group of extradimensional Pokémon originating from Ultra Space.}
#'	\item{`family`}{`character` Legendary / Mythical family group of the Pokemon. This refers to the group or lineage the Legendary or Mythical Pokémon belongs to. NA if the Pokemon does not belong to a family group.}
#'	\item{`size`}{`character` Legendary / Mythical family size. This refers to the size of the Legendary or Mythical family group the Pokémon belongs to. NA if the Pokemon does not belong to a family group.}
#' }
#' @source [List of Pokémon by National Pokédex number. In Bulbapedia.](https://bulbapedia.bulbagarden.net/wiki/List_of_Pokémon_by_National_Pokédex_number)
#'
#' @references [National Pokédex. In Bulbapedia.](https://bulbapedia.bulbagarden.net/wiki/National_Pokédex)
#'
#' @examples
#' data(nationalDex)
"nationalDex"
#' Legendary and Mythical Pokémon Groupings
#'
#' This dataset contains information about Legendary and Mythical Pokémon,
#' which are a special group of Pokémon that are incredibly rare and often very powerful.
#' These Pokémon are categorized by their family groupings and sizes.
#' Family groupings are often based on common themes or characteristics among the Pokémon.
#' 
#' For example, the 'Tao trio' refers to Reshiram, Zekrom, and Kyurem,
#' which are associated with the concept of yin, yang, and wuji.
#' 
#' The 'Super-ancient Pokémon' refers to Kyogre, Groudon, and Rayquaza,
#' which are ancient Pokémon with powerful weather abilities.
#' 
#' The 'Paradox duo' refers to Koraidon and Miraidon, which are associated with different timelines.
#' @format A data frame with 3 variables:
#' \describe{
#'	\item{`family`}{`character` The family grouping of the Pokémon. This refers to the thematic or characteristic-based group that the Pokémon belongs to. Examples include 'Tao trio', 'Super-ancient Pokémon', 'Paradox duo', etc.}
#'	\item{`name`}{`character` The name of the individual Pokémon within the family grouping. This is the common name used to identify a particular Pokémon.}
#'	\item{`size`}{`character` The size category of the family grouping. This refers to the number of Pokémon in the family grouping. Categories include 'duos', 'trios', 'quartets', and 'quintets'.}
#' }
#' @source [Groups of Legendary and Mythical Pokémon. In Bulbapedia.](https://bulbapedia.bulbagarden.net/wiki/Groups_of_Legendary_and_Mythical_Pok%C3%A9mon)
#'
#'
#'
#' @examples
#' data(groups)
"groups"
#' Pokemon Stats (Wide Format)
#'
#' This dataset is a wide format version of the `stats` dataset. It contains the base stats of Pokémon, including various forms and sizes of Pokémon, across different generations. Base stats are an important defining characteristic of each Pokémon species. They determine the potential of each Pokémon in terms of their HP (Hit Points), Attack, Defense, Speed, and Special abilities. These stats can be influenced by other factors such as level, nature, and effort values.
#' @format A data frame with 49 variables:
#' \describe{
#'	\item{`ndex`}{`integer` National Pokédex number. This is the unique identifier for each Pokémon in the National Pokédex.}
#'	\item{`name`}{`character` Pokémon name. This is the common name used to identify a particular Pokémon.}
#'	\item{`Mega`}{`character` The Mega form. These are special forms that certain Pokémon can take.}
#'	\item{`MegaOrPrimal`}{`character` Indicates if the Pokémon is in a Mega or Primal form. These are special forms that certain Pokémon can take.}
#'	\item{`regional`}{`character` The regional form of the Pokémon. This refers to the variations of Pokémon that appear differently and have different attributes compared to their counterparts in other regions.}
#'	\item{`HP_I`}{`integer` Hit Points for Generation I. This determines how much damage a Pokémon can receive before fainting.}
#'	\item{`HP_VI`}{`integer` Hit Points for Generation VI. This determines how much damage a Pokémon can receive before fainting.}
#'	\item{`HP_VII`}{`integer` Hit Points for Generation VII. This determines how much damage a Pokémon can receive before fainting.}
#'	\item{`HP_VIII`}{`integer` Hit Points for Generation VIII. This determines how much damage a Pokémon can receive before fainting.}
#'	\item{`HP_IX`}{`integer` Hit Points for Generation IX. This determines how much damage a Pokémon can receive before fainting.}
#'	\item{`HP_II-V`}{`integer` Hit Points for Generations II to V. This determines how much damage a Pokémon can receive before fainting.}
#'	\item{`Attack_I`}{`integer` Attack strength for Generation I. This determines how much damage a Pokémon can deal with physical moves.}
#'	\item{`Attack_VI`}{`integer` Attack strength for Generation VI. This determines how much damage a Pokémon can deal with physical moves.}
#'	\item{`Attack_VII`}{`integer` Attack strength for Generation VII. This determines how much damage a Pokémon can deal with physical moves.}
#'	\item{`Attack_VIII`}{`integer` Attack strength for Generation VIII. This determines how much damage a Pokémon can deal with physical moves.}
#'	\item{`Attack_IX`}{`integer` Attack strength for Generation IX. This determines how much damage a Pokémon can deal with physical moves.}
#'	\item{`Attack_II-V`}{`integer` Attack strength for Generations II to V. This determines how much damage a Pokémon can deal with physical moves.}
#'	\item{`Defense_I`}{`integer` Defensive strength for Generation I. This determines how much damage a Pokémon can resist from physical moves.}
#'	\item{`Defense_VI`}{`integer` Defensive strength for Generation VI. This determines how much damage a Pokémon can resist from physical moves.}
#'	\item{`Defense_VII`}{`integer` Defensive strength for Generation VII. This determines how much damage a Pokémon can resist from physical moves.}
#'	\item{`Defense_VIII`}{`integer` Defensive strength for Generation VIII. This determines how much damage a Pokémon can resist from physical moves.}
#'	\item{`Defense_IX`}{`integer` Defensive strength for Generation IX. This determines how much damage a Pokémon can resist from physical moves.}
#'	\item{`Defense_II-V`}{`integer` Defensive strength for Generations II to V. This determines how much damage a Pokémon can resist from physical moves.}
#'	\item{`Speed_I`}{`integer` Speed for Generation I. This determines the order of Pokémon that can act in battle.}
#'	\item{`Speed_VI`}{`integer` Speed for Generation VI. This determines the order of Pokémon that can act in battle.}
#'	\item{`Speed_VII`}{`integer` Speed for Generation VII. This determines the order of Pokémon that can act in battle.}
#'	\item{`Speed_VIII`}{`integer` Speed for Generation VIII. This determines the order of Pokémon that can act in battle.}
#'	\item{`Speed_IX`}{`integer` Speed for Generation IX. This determines the order of Pokémon that can act in battle.}
#'	\item{`Speed_II-V`}{`integer` Speed for Generations II to V. This determines the order of Pokémon that can act in battle.}
#'	\item{`Special_I`}{`integer` Special attack or special defense strength for Generation I. This determines how much damage a Pokémon can deal with special moves or resist from special moves. Note that this stat is combined into one in Generation I.}
#'	\item{`Total_I`}{`integer` Total of all stats for Generation I. This is the sum of all the base stats of a Pokémon.}
#'	\item{`Total_VI`}{`integer` Total of all stats for Generation VI. This is the sum of all the base stats of a Pokémon.}
#'	\item{`Total_VII`}{`integer` Total of all stats for Generation VII. This is the sum of all the base stats of a Pokémon.}
#'	\item{`Total_VIII`}{`integer` Total of all stats for Generation VIII. This is the sum of all the base stats of a Pokémon.}
#'	\item{`Total_IX`}{`integer` Total of all stats for Generation IX. This is the sum of all the base stats of a Pokémon.}
#'	\item{`Total_II-V`}{`integer` Total of all stats for Generations II to V. This is the sum of all the base stats of a Pokémon.}
#'	\item{`Average_I`}{`numeric` Average of all stats for Generation I. This is the average value of all the base stats of a Pokémon.}
#'	\item{`Average_VI`}{`numeric` Average of all stats for Generation VI. This is the average value of all the base stats of a Pokémon.}
#'	\item{`Average_VII`}{`numeric` Average of all stats for Generation VII. This is the average value of all the base stats of a Pokémon.}
#'	\item{`Average_VIII`}{`numeric` Average of all stats for Generation VIII. This is the average value of all the base stats of a Pokémon.}
#'	\item{`Average_IX`}{`numeric` Average of all stats for Generation IX. This is the average value of all the base stats of a Pokémon.}
#'	\item{`Average_II-V`}{`numeric` Average of all stats for Generations II to V. This is the average value of all the base stats of a Pokémon.}
#'	\item{`SpAttack_VI`}{`integer` Special Attack strength for Generation VI. This determines how much damage a Pokémon can deal with special moves.}
#'	\item{`SpAttack_VII`}{`integer` Special Attack strength for Generation VII. This determines how much damage a Pokémon can deal with special moves.}
#'	\item{`SpAttack_VIII`}{`integer` Special Attack strength for Generation VIII. This determines how much damage a Pokémon can deal with special moves.}
#'	\item{`SpAttack_IX`}{`integer` Special Attack strength for Generation IX. This determines how much damage a Pokémon can deal with special moves.}
#'	\item{`SpAttack_II-V`}{`integer` Special Attack strength for Generations II to V. This determines how much damage a Pokémon can deal with special moves.}
#'	\item{`SpDefense_VI`}{`integer` Special Defense strength for Generation VI. This determines how much damage a Pokémon can resist from special moves.}
#'	\item{`SpDefense_VII`}{`integer` Special Defense strength for Generation VII. This determines how much damage a Pokémon can resist from special moves.}
#'	\item{`SpDefense_VIII`}{`integer` Special Defense strength for Generation VIII. This determines how much damage a Pokémon can resist from special moves.}
#'	\item{`SpDefense_IX`}{`integer` Special Defense strength for Generation IX. This determines how much damage a Pokémon can resist from special moves.}
#'	\item{`SpDefense_II-V`}{`integer` Special Defense strength for Generations II to V. This determines how much damage a Pokémon can resist from special moves.}
#' }
#' @source [List of Pokémon by base stats (Generation I). In Bulbapedia.](https://bulbapedia.bulbagarden.net/wiki/List_of_Pok%C3%A9mon_by_base_stats_(Generation_I))
#' [List of Pokémon by base stats (Generation II-V). In Bulbapedia.](https://bulbapedia.bulbagarden.net/wiki/List_of_Pok%C3%A9mon_by_base_stats_(Generation_II-V))
#' [List of Pokémon by base stats (Generation VI). In Bulbapedia.](https://bulbapedia.bulbagarden.net/wiki/List_of_Pok%C3%A9mon_by_base_stats_(Generation_VI))
#' [List of Pokémon by base stats (Generation VII). In Bulbapedia.](https://bulbapedia.bulbagarden.net/wiki/List_of_Pok%C3%A9mon_by_base_stats_(Generation_VII))
#' [List of Pokémon by base stats (Generation VIII). In Bulbapedia.](https://bulbapedia.bulbagarden.net/wiki/List_of_Pok%C3%A9mon_by_base_stats_(Generation_VIII))
#' [List of Pokémon by base stats (Generation IX). In Bulbapedia.](https://bulbapedia.bulbagarden.net/wiki/List_of_Pok%C3%A9mon_by_base_stats_(Generation_IX))
#'
#'
#'
#' @examples
#' data(statsWide)
"statsWide"
#' Pokemon Stats
#'
#' This dataset contains the base stats of Pokémon, including various forms and sizes of Pokémon. Base stats are an important defining characteristic of each Pokémon species. They determine the potential of each Pokémon in terms of their HP (Hit Points), Attack, Defense, Speed, and Special abilities. These stats can be influenced by other factors such as level, nature, and effort values.
#' @format A data frame with 14 variables:
#' \describe{
#'	\item{`ndex`}{`integer` National Pokédex number. This is the unique identifier for each Pokémon in the National Pokédex.}
#'	\item{`name`}{`character` Pokémon name. This is the common name used to identify a particular Pokémon.}
#'	\item{`HP`}{`integer` Hit Points. This determines how much damage a Pokémon can receive before fainting.}
#'	\item{`Attack`}{`integer` Attack strength. This determines how much damage a Pokémon can deal with physical moves.}
#'	\item{`Defense`}{`integer` Defensive strength. This determines how much damage a Pokémon can resist from physical moves.}
#'	\item{`Speed`}{`integer` Speed. This determines the order of Pokémon that can act in battle.}
#'	\item{`Special`}{`integer` Special attack or special defense strength. This determines how much damage a Pokémon can deal with special moves or resist from special moves. Note that this stat is combined into one in Generation I.}
#'	\item{`Total`}{`integer` Total of all stats. This is the sum of all the base stats of a Pokémon.}
#'	\item{`Average`}{`numeric` Average of all stats. This is the average value of all the base stats of a Pokémon.}
#'	\item{`Gen`}{`factor` Generation. This indicates the generation of games in which the Pokémon was introduced.}
#'	\item{`SpAttack`}{`integer` Special Attack strength. This determines how much damage a Pokémon can deal with special moves. This stat is not applicable for Generation I as 'Special' stat is used instead.}
#'	\item{`SpDefense`}{`integer` Special Defense strength. This determines how much damage a Pokémon can resist from special moves. This stat is not applicable for Generation I as 'Special' stat is used instead.}
#'	\item{`Mega`}{`character` The Mega form. These are special forms that certain Pokémon can take.}
#'	\item{`MegaOrPrimal`}{`character` Indicates if the Pokémon is in a Mega or Primal form. These are special forms that certain Pokémon can take.}
#'	\item{`regional`}{`character` The regional form of the Pokémon. This refers to the variations of Pokémon that appear differently and have different attributes compared to their counterparts in other regions.}
#' }
#' @source [List of Pokémon by base stats (Generation I). In Bulbapedia.](https://bulbapedia.bulbagarden.net/wiki/List_of_Pok%C3%A9mon_by_base_stats_(Generation_I))
#' [List of Pokémon by base stats (Generation II-V). In Bulbapedia.](https://bulbapedia.bulbagarden.net/wiki/List_of_Pok%C3%A9mon_by_base_stats_(Generation_II-V))
#' [List of Pokémon by base stats (Generation VI). In Bulbapedia.](https://bulbapedia.bulbagarden.net/wiki/List_of_Pok%C3%A9mon_by_base_stats_(Generation_VI))
#' [List of Pokémon by base stats (Generation VII). In Bulbapedia.](https://bulbapedia.bulbagarden.net/wiki/List_of_Pok%C3%A9mon_by_base_stats_(Generation_VII))
#' [List of Pokémon by base stats (Generation VIII). In Bulbapedia.](https://bulbapedia.bulbagarden.net/wiki/List_of_Pok%C3%A9mon_by_base_stats_(Generation_VIII))
#' [List of Pokémon by base stats (Generation IX). In Bulbapedia.](https://bulbapedia.bulbagarden.net/wiki/List_of_Pok%C3%A9mon_by_base_stats_(Generation_IX))
#'
#'
#'
#' @examples
#' data(stats)
"stats"
#' Pokemon Evolution Dataset
#'
#' This dataset contains information about Pokémon evolution and family groupings.
#' It provides a comprehensive view of the evolution tree of each Pokémon,
#' making it an excellent resource for understanding how different Pokémon are related to each other and how they evolve.
#' The dataset includes Pokémon from all generations and covers various forms and regional variants.
#' @format A data frame with the following variables:
#' \describe{
#'	\item{`family`}{`character` The family to which the Pokemon belongs. This refers to the group or lineage the Pokémon belongs to, often based on common themes or characteristics among the Pokémon.}
#'	\item{`base`}{`character` The prior form of the pokemon or the base form. This is the form from which the Pokémon evolves.}
#'	\item{`form`}{`character` The specific form of the Pokemon. This refers to the different physical forms that Pokémon can take. NA if the Pokemon does not have a special form.}
#'	\item{`method`}{`character` The method of evolution. This refers to the specific condition or trigger that causes the Pokémon to evolve. Examples include leveling up, exposure to an evolution stone, trading, and more.}
#'	\item{`evo`}{`character` The next stage of the Pokemon. This is the form that the Pokémon evolves into.}
#'	\item{`evoForm`}{`character` The form of next stage of the Pokemon. This refers to the specific form that the Pokémon takes after evolution. NA if the Pokemon does not change form upon evolution.}
#'	\item{`transition`}{`character` The transition stage of the Pokemon. This refers to any intermediate stages that occur during the Pokémon's evolution.}
#'	\item{`first`}{`character` The first form of the Pokemon. This is the initial form of the Pokémon before any evolutions.}
#'	\item{`firstForm`}{`character` The specific first form of the Pokemon. This refers to the specific form that the Pokémon takes in its initial stage. NA if the Pokemon does not have a special form at the initial stage.}
#'	\item{`regional`}{`character` The regional form of the Pokemon. This refers to the variations of Pokémon that appear differently and have different attributes compared to their counterparts in other regions. NA if the Pokemon does not have a regional form.}
#'	\item{`evoRegional`}{`character` The regional evolved form of the Pokemon. This refers to the regional form that the Pokémon takes after evolution. NA if the Pokemon does not change form upon evolution in a specific region.}
#'	\item{`firstRegional`}{`character` The regional first form of the Pokemon. This refers to the regional form that the Pokémon takes in its initial stage. NA if the Pokemon does not have a regional form at the initial stage.}
#' }
#' @source [List of Pokémon by evolution family. In Bulbapedia.](https://bulbapedia.bulbagarden.net/wiki/List_of_Pok%C3%A9mon_by_evolution_family)
#'
#' @references [Methods of evolution. In Bulbapedia.](https://bulbapedia.bulbagarden.net/wiki/Methods_of_evolution)
#'
#' @examples
#' data(family)
"family"
#' Extended Pokemon Evolution Dataset
#'
#' This dataset contains detailed information about Pokémon evolution and family groupings. It provides a comprehensive view of the evolution tree of each Pokémon, making it an excellent resource for understanding how different Pokémon are related to each other and how they evolve. The dataset includes Pokémon from all generations and covers various forms and regional variants.
#' 
#' While this dataset loses the hierarchical structure of the evolution tree, it is particularly useful for identifying which Pokémon belong to each family. It provides a flat structure that can be easily filtered and sorted to find specific Pokémon and their families.
#' 
#' Note: The `family.x` and `family.y` variables need to be reconciled to ensure consistency across the dataset.
#' @format A data frame with the following variables:
#' \describe{
#'	\item{`family.x`}{`character` The family of the Pokemon. This refers to the group or lineage the Pokémon belongs to, often based on common themes or characteristics among the Pokémon.}
#'	\item{`transition`}{`character` The transition stage of the Pokemon. This refers to any intermediate stages that occur during the Pokémon's evolution.}
#'	\item{`first`}{`character` The first form of the Pokemon. This is the initial form of the Pokémon before any evolutions.}
#'	\item{`firstForm`}{`character` The first form of the Pokemon if it has multiple forms. This refers to the specific form that the Pokémon takes in its initial stage. NA if the Pokemon does not have a special form at the initial stage.}
#'	\item{`firstRegional`}{`character` The first regional form of the Pokemon. This refers to the regional form that the Pokémon takes in its initial stage. NA if the Pokemon does not have a regional form at the initial stage.}
#'	\item{`name`}{`character` The name of the Pokemon. This is the common name used to identify a particular Pokémon.}
#'	\item{`form`}{`character` The form of the Pokemon. This refers to the different physical forms that Pokémon can take. NA if the Pokemon does not have a special form.}
#'	\item{`regional`}{`character` The regional form of the Pokemon. This refers to the variations of Pokémon that appear differently and have different attributes compared to their counterparts in other regions. NA if the Pokemon does not have a regional form.}
#'	\item{`stage`}{`character` The stage of the Pokemon. This refers to the stage in the Pokémon's evolution process, such as 'base', 'stage 1', 'stage 2', etc.}
#'	\item{`family.y`}{`character` The legendary family of the Pokemon. This refers to the group or lineage the Legendary or Mythical Pokémon belongs to. NA if the Pokemon does not belong to a family group.}
#'	\item{`size`}{`character` The size of the legendary family. This refers to the size of the Legendary or Mythical family group the Pokémon belongs to. NA if the Pokemon does not belong to a family group.}
#' }
#' @source [Methods of evolution. In Bulbapedia.](https://bulbapedia.bulbagarden.net/wiki/Methods_of_evolution)
#'
#'
#'
#' @examples
#' data(familyLong)
"familyLong"
#' Pokémon National Dex information in multiple languages
#'
#' This dataset contains the names of Pokémon in various languages.
#' Each Pokémon has a unique name in each language, and these names often reflect the culture and
#' language patterns of their respective regions. The dataset includes names in multiple languages,
#' including but not limited to English, Japanese, German, French, Spanish, Italian, Korean, Chinese,
#' Brazilian Portuguese, Turkish, Russian, Thai, and Hindi. The language columns are in the format of
#' `<Language>_<language subset>`. If there is no subset, it's `<Language>`.
#' @format A data frame with 37 variables:
#' \describe{
#'	\item{`ndex`}{`integer` The National Pokédex number of the Pokémon. This is the unique identifier for each Pokémon in the National Pokédex.}
#'	\item{`name`}{`character` The English name of the Pokémon.}
#'	\item{`form`}{`character` The form of the Pokémon. This refers to the different physical forms that Pokémon can take. 'NA' if the Pokémon does not have a special form.}
#'	\item{`regional`}{`character` The regional form of the Pokémon. This refers to the variations of Pokémon that appear differently and have different attributes compared to their counterparts in other regions. 'NA' if the Pokémon does not have a regional form.}
#'	\item{`type`}{`character` The primary type of the Pokémon. Each Pokémon has a primary type which determines the Pokémon's strengths and weaknesses.}
#'	\item{`type2`}{`character` The secondary type of the Pokémon. Some Pokémon may have a secondary type, which further influences the Pokémon's strengths and weaknesses. 'NA' if the Pokémon does not have a secondary type.}
#'	\item{`generation`}{`integer` The generation of the Pokémon. This refers to the generation of games in which the Pokémon was first introduced.}
#'	\item{`isLegendary`}{`logical` A boolean indicating if the Pokémon is Legendary. Legendary Pokémon are a group of incredibly rare and often very powerful Pokémon.}
#'	\item{`isMythical`}{`logical` A boolean indicating if the Pokémon is Mythical. Mythical Pokémon are a related but separate group of Pokémon, which are usually event-exclusive.}
#'	\item{`isUltraBeast`}{`logical` A boolean indicating if the Pokémon is an Ultra Beast. Ultra Beasts is a term introduced in Generation VII to classify seven known Pokémon.}
#'	\item{`family`}{`character` The family of the Pokémon. This refers to the group or lineage the Pokémon belongs to, often based on common themes or characteristics among the Pokémon.}
#'	\item{`size`}{`character` The size of the Pokémon. This refers to the height and weight of the Pokémon.}
#'	\item{`Japanese_Kana`}{`character` The Japanese Kana name of the Pokémon.}
#'	\item{`Japanese_Hepburn`}{`character` The Japanese Hepburn name of the Pokémon.}
#'	\item{`Japanese_Trademarked`}{`character` The Japanese Trademarked name of the Pokémon.}
#'	\item{`German`}{`character` The German name of the Pokémon.}
#'	\item{`French`}{`character` The French name of the Pokémon.}
#'	\item{`Spanish`}{`character` The Spanish name of the Pokémon.}
#'	\item{`Italian`}{`character` The Italian name of the Pokémon.}
#'	\item{`Korean_Hangul`}{`character` The Korean Hangul name of the Pokémon.}
#'	\item{`Korean_Revised`}{`character` The Korean Revised name of the Pokémon.}
#'	\item{`Korean_McCune-Reischauer`}{`character` The Korean McCune-Reischauer name of the Pokémon.}
#'	\item{`Korean_Official`}{`character` The Korean Official name of the Pokémon.}
#'	\item{`Chinese_Traditional`}{`character` The Chinese Traditional name of the Pokémon.}
#'	\item{`Chinese_Simplified`}{`character` The Chinese Simplified name of the Pokémon.}
#'	\item{`Chinese_Pinyin`}{`character` The Chinese Pinyin name of the Pokémon.}
#'	\item{`Chinese_Yale`}{`character` The Chinese Yale name of the Pokémon.}
#'	\item{`Chinese_Former_names`}{`character` The Chinese Former names of the Pokémon.}
#'	\item{`Brazilian_Portuguese_Brazilian_Portuguese`}{`character` The Brazilian Portuguese name of the Pokémon.}
#'	\item{`Turkish`}{`character` The Turkish name of the Pokémon.}
#'	\item{`Russian_Cyrillic`}{`character` The Russian Cyrillic name of the Pokémon.}
#'	\item{`Russian_Romanization`}{`character` The Russian Romanization name of the Pokémon.}
#'	\item{`Thai`}{`character` The Thai name of the Pokémon.}
#'	\item{`Thai_RTGS`}{`character` The Thai RTGS name of the Pokémon.}
#'	\item{`Hindi_Devanagari`}{`character` The Hindi Devanāgarī name of the Pokémon.}
#'	\item{`Hindi_Transliteration`}{`character` The Hindi Transliteration name of the Pokémon.}
#'	\item{`Hindi_Romanization`}{`character` The Hindi Romanization name of the Pokémon.}
#' }
#' @source [List of Pokémon by National Pokédex number. In Bulbapedia.](https://bulbapedia.bulbagarden.net/wiki/List_of_Pok%C3%A9mon_by_National_Pok%C3%A9dex_number)
#' [List of Japanese Pokémon names. In Bulbapedia.](https://bulbapedia.bulbagarden.net/wiki/List_of_Japanese_Pok%C3%A9mon_names)
#' [List of German Pokémon names. In Bulbapedia.](https://bulbapedia.bulbagarden.net/wiki/List_of_German_Pok%C3%A9mon_names)
#' [List of French Pokémon names. In Bulbapedia.](https://bulbapedia.bulbagarden.net/wiki/List_of_French_Pok%C3%A9mon_names)
#' [List of Spanish Pokémon names. In Bulbapedia.](https://bulbapedia.bulbagarden.net/wiki/List_of_Spanish_Pok%C3%A9mon_names)
#' [List of Italian Pokémon names. In Bulbapedia.](https://bulbapedia.bulbagarden.net/wiki/List_of_Italian_Pok%C3%A9mon_names)
#' [List of Korean Pokémon names. In Bulbapedia.](https://bulbapedia.bulbagarden.net/wiki/List_of_Korean_Pok%C3%A9mon_names)
#' [List of Chinese Pokémon names. In Bulbapedia.](https://bulbapedia.bulbagarden.net/wiki/List_of_Chinese_Pok%C3%A9mon_names)
#' [List of Brazilian Portuguese Pokémon names. In Bulbapedia.](https://bulbapedia.bulbagarden.net/wiki/List_of_Brazilian_Portuguese_Pok%C3%A9mon_names)
#' [List of Turkish Pokémon names. In Bulbapedia.](https://bulbapedia.bulbagarden.net/wiki/List_of_Turkish_Pok%C3%A9mon_names)
#' [List of Russian Pokémon names. In Bulbapedia.](https://bulbapedia.bulbagarden.net/wiki/List_of_Russian_Pok%C3%A9mon_names)
#' [List of Thai Pokémon names. In Bulbapedia.](https://bulbapedia.bulbagarden.net/wiki/List_of_Thai_Pok%C3%A9mon_names)
#' [List of Hindi Pokémon names. In Bulbapedia.](https://bulbapedia.bulbagarden.net/wiki/List_of_Hindi_Pok%C3%A9mon_names)
#'
#'
#'
#' @examples
#' data(languages)
"languages"
#' Pokémon Information from the Regional Dex
#'
#' This dataset contains information about Pokémon as per the Regional Pokédex.
#' The regionalDex columns are in the format of `<Game>_<Region>_<DexName>`.
#' If the data is missing, it is represented as `NA`.
#' @format A data frame with the following variables:
#' \describe{
#'	\item{`ndex`}{`integer` The National Pokédex number of the Pokémon.}
#'	\item{`name`}{`character` The name of the Pokémon.}
#'	\item{`form`}{`character` The form of the Pokémon. This refers to the different physical forms that Pokémon can take.}
#'	\item{`regional`}{`character` The regional form of the Pokémon. This refers to the variations of Pokémon that appear differently and have different attributes compared to their counterparts in other regions.}
#'	\item{`type`}{`character` The primary type of the Pokémon. Each Pokémon has a primary type which determines the Pokémon's strengths and weaknesses.}
#'	\item{`type2`}{`character` The secondary type of the Pokémon. Some Pokémon may have a secondary type, which further influences the Pokémon's strengths and weaknesses.}
#'	\item{`generation`}{`integer` The generation of the Pokémon. This refers to the generation of games in which the Pokémon was first introduced.}
#'	\item{`isLegendary`}{`logical` A boolean indicating if the Pokémon is Legendary. Legendary Pokémon are a group of incredibly rare and often very powerful Pokémon.}
#'	\item{`isMythical`}{`logical` A boolean indicating if the Pokémon is Mythical. Mythical Pokémon are a related but separate group of Pokémon, which are usually event-exclusive.}
#'	\item{`isUltraBeast`}{`logical` A boolean indicating if the Pokémon is an Ultra Beast. Ultra Beasts is a term introduced in Generation VII to classify seven known Pokémon.}
#'	\item{`family`}{`character` The family of the Pokémon. This refers to the group or lineage the Pokémon belongs to, often based on common themes or characteristics among the Pokémon.}
#'	\item{`size`}{`character` The size of the Pokémon. This refers to the height and weight of the Pokémon.}
#'	\item{`NA_Kanto_Kdex`}{`integer` The Kanto Pokédex number. This is the number assigned to the Pokémon in the Kanto Regional Pokédex.}
#'	\item{`NA_Johto_Jdex`}{`integer` The Johto Pokédex number. This is the number assigned to the Pokémon in the Johto Regional Pokédex.}
#'	\item{`GenerationIII_Hoenn_Hdex`}{`integer` The Hoenn Pokédex number in Generation III. This is the number assigned to the Pokémon in the Hoenn Regional Pokédex in Generation III games.}
#'	\item{`GenerationVI_Hoenn_Hdex`}{`integer` The Hoenn Pokédex number in Generation VI. This is the number assigned to the Pokémon in the Hoenn Regional Pokédex in Generation VI games.}
#'	\item{`NA_Sinnoh_Sdex`}{`integer` The Sinnoh Pokédex number. This is the number assigned to the Pokémon in the Sinnoh Regional Pokédex.}
#'	\item{`BlackandWhite_Unova_Udex`}{`integer` The Unova Pokédex number in Black and White. This is the number assigned to the Pokémon in the Unova Regional Pokédex in Pokémon Black and White.}
#'	\item{`Black2andWhite2_Unova_Udex`}{`integer` The Unova Pokédex number in Black 2 and White 2. This is the number assigned to the Pokémon in the Unova Regional Pokédex in Pokémon Black 2 and White 2.}
#'	\item{`NA_Blueberry_BBdex`}{`integer` The Blueberry Pokédex number. This is the number assigned to the Pokémon in the Blueberry Regional Pokédex.}
#'	\item{`NA_Kalos_CeKdex`}{`integer` The Central Kalos Pokédex number. This is the number assigned to the Pokémon in the Central Kalos Regional Pokédex.}
#'	\item{`NA_Kalos_CoKdex`}{`integer` The Coastal Kalos Pokédex number. This is the number assigned to the Pokémon in the Coastal Kalos Regional Pokédex.}
#'	\item{`NA_Kalos_MoKdex`}{`integer` The Mountain Kalos Pokédex number. This is the number assigned to the Pokémon in the Mountain Kalos Regional Pokédex.}
#'	\item{`SunandMoon_Alola_Adex`}{`integer` The Alola Pokédex number in Sun and Moon. This is the number assigned to the Pokémon in the Alola Regional Pokédex in Pokémon Sun and Moon.}
#'	\item{`SunandMoon_Alola_Melemele`}{`integer` The Melemele Pokédex number in Sun and Moon. This is the number assigned to the Pokémon in the Melemele Regional Pokédex in Pokémon Sun and Moon.}
#'	\item{`SunandMoon_Alola_Akala`}{`integer` The Akala Pokédex number in Sun and Moon. This is the number assigned to the Pokémon in the Akala Regional Pokédex in Pokémon Sun and Moon.}
#'	\item{`SunandMoon_Alola_Ulaula`}{`integer` The Ula'ula Pokédex number in Sun and Moon. This is the number assigned to the Pokémon in the Ula'ula Regional Pokédex in Pokémon Sun and Moon.}
#'	\item{`SunandMoon_Alola_Poni`}{`integer` The Poni Pokédex number in Sun and Moon. This is the number assigned to the Pokémon in the Poni Regional Pokédex in Pokémon Sun and Moon.}
#'	\item{`UltraSunandUltraMoon_Alola_Adex`}{`integer` The Alola Pokédex number in Ultra Sun and Ultra Moon. This is the number assigned to the Pokémon in the Alola Regional Pokédex in Pokémon Ultra Sun and Ultra Moon.}
#'	\item{`UltraSunandUltraMoon_Alola_Melemele`}{`integer` The Melemele Pokédex number in Ultra Sun and Ultra Moon. This is the number assigned to the Pokémon in the Melemele Regional Pokédex in Pokémon Ultra Sun and Ultra Moon.}
#'	\item{`UltraSunandUltraMoon_Alola_Akala`}{`integer` The Akala Pokédex number in Ultra Sun and Ultra Moon. This is the number assigned to the Pokémon in the Akala Regional Pokédex in Pokémon Ultra Sun and Ultra Moon.}
#'	\item{`UltraSunandUltraMoon_Alola_Ulaula`}{`integer` The Ula'ula Pokédex number in Ultra Sun and Ultra Moon. This is the number assigned to the Pokémon in the Ula'ula Regional Pokédex in Pokémon Ultra Sun and Ultra Moon.}
#'	\item{`UltraSunandUltraMoon_Alola_Poni`}{`integer` The Poni Pokédex number in Ultra Sun and Ultra Moon. This is the number assigned to the Pokémon in the Poni Regional Pokédex in Pokémon Ultra Sun and Ultra Moon.}
#'	\item{`NA_Galar_Gdex`}{`integer` The Galar Pokédex number. This is the number assigned to the Pokémon in the Galar Regional Pokédex.}
#'	\item{`NA_IsleofArmor_IoAdex`}{`integer` The Isle of Armor Pokédex number. This is the number assigned to the Pokémon in the Isle of Armor Regional Pokédex.}
#'	\item{`NA_CrownTundra_CTdex`}{`integer` The Crown Tundra Pokédex number. This is the number assigned to the Pokémon in the Crown Tundra Regional Pokédex.}
#'	\item{`NA_Hisui_LAdex`}{`integer` The Hisui Pokédex number. This is the number assigned to the Pokémon in the Hisui Regional Pokédex.}
#'	\item{`NA_Paldea_Pdex`}{`integer` The Paldea Pokédex number. This is the number assigned to the Pokémon in the Paldea Regional Pokédex.}
#'	\item{`NA_Kitakami_Kdex`}{`integer` The Kitakami Pokédex number. This is the number assigned to the Pokémon in the Kitakami Regional Pokédex.}
#' }
#' @source [List of Pokémon by Kanto Pokédex number. In Bulbapedia.](https://bulbapedia.bulbagarden.net/wiki/List_of_Pok%C3%A9mon_by_Kanto_Pok%C3%A9dex_number)
#' [List of Pokémon by New Pokédex number. In Bulbapedia.](https://bulbapedia.bulbagarden.net/wiki/List_of_Pok%C3%A9mon_by_New_Pok%C3%A9dex_number)
#' [List of Pokémon by Johto Pokédex number. In Bulbapedia.](https://bulbapedia.bulbagarden.net/wiki/List_of_Pok%C3%A9mon_by_Johto_Pok%C3%A9dex_number)
#' [List of Pokémon by Hoenn Pokédex number (Generation III). In Bulbapedia.](https://bulbapedia.bulbagarden.net/wiki/List_of_Pok%C3%A9mon_by_Hoenn_Pok%C3%A9dex_number_(Generation_III))
#' [List of Pokémon by Hoenn Pokédex number (Generation VI). In Bulbapedia.](https://bulbapedia.bulbagarden.net/wiki/List_of_Pok%C3%A9mon_by_Hoenn_Pok%C3%A9dex_number_(Generation_VI))
#' [List of Pokémon by Sinnoh Pokédex number. In Bulbapedia.](https://bulbapedia.bulbagarden.net/wiki/List_of_Pok%C3%A9mon_by_Sinnoh_Pok%C3%A9dex_number)
#' [List of Pokémon by Unova Pokédex number (Black and White). In Bulbapedia.](https://bulbapedia.bulbagarden.net/wiki/List_of_Pok%C3%A9mon_by_Unova_Pok%C3%A9dex_number_(Black_and_White))
#' [List of Pokémon by Unova Pokédex number (Black 2 and White 2). In Bulbapedia.](https://bulbapedia.bulbagarden.net/wiki/List_of_Pok%C3%A9mon_by_Unova_Pok%C3%A9dex_number_(Black_2_and_White_2))
#' [List of Pokémon by Blueberry Pokédex number. In Bulbapedia.](https://bulbapedia.bulbagarden.net/wiki/List_of_Pok%C3%A9mon_by_Blueberry_Pok%C3%A9dex_number)
#' [List of Pokémon by Kalos Pokédex number. In Bulbapedia.](https://bulbapedia.bulbagarden.net/wiki/List_of_Pok%C3%A9mon_by_Kalos_Pok%C3%A9dex_number)
#' [List of Pokémon by Alola Pokédex number (Sun and Moon). In Bulbapedia.](https://bulbapedia.bulbagarden.net/wiki/List_of_Pok%C3%A9mon_by_Alola_Pok%C3%A9dex_number_(Sun_and_Moon))
#' [List of Pokémon by Alola Pokédex number (Ultra Sun and Ultra Moon). In Bulbapedia.](https://bulbapedia.bulbagarden.net/wiki/List_of_Pok%C3%A9mon_by_Alola_Pok%C3%A9dex_number_(Ultra_Sun_and_Ultra_Moon))
#' [List of Pokémon by Galar Pokédex number. In Bulbapedia.](https://bulbapedia.bulbagarden.net/wiki/List_of_Pok%C3%A9mon_by_Galar_Pok%C3%A9dex_number)
#' [List of Pokémon by Isle of Armor Pokédex number. In Bulbapedia.](https://bulbapedia.bulbagarden.net/wiki/List_of_Pok%C3%A9mon_by_Isle_of_Armor_Pok%C3%A9dex_number)
#' [List of Pokémon by Crown Tundra Pokédex number. In Bulbapedia.](https://bulbapedia.bulbagarden.net/wiki/List_of_Pok%C3%A9mon_by_Crown_Tundra_Pok%C3%A9dex_number)
#' [List of Pokémon by Hisui Pokédex number. In Bulbapedia.](https://bulbapedia.bulbagarden.net/wiki/List_of_Pok%C3%A9mon_by_Hisui_Pok%C3%A9dex_number)
#' [List of Pokémon by Paldea Pokédex number. In Bulbapedia.](https://bulbapedia.bulbagarden.net/wiki/List_of_Pok%C3%A9mon_by_Paldea_Pok%C3%A9dex_number)
#' [List of Pokémon by Kitakami Pokédex number. In Bulbapedia.](https://bulbapedia.bulbagarden.net/wiki/List_of_Pok%C3%A9mon_by_Kitakami_Pok%C3%A9dex_number)
#'
#'
#'
#' @examples
#' data(regionalDex)
"regionalDex"
#' Pokemon Types Dataset
#'
#' This dataset contains information about various Pokemon types.
#' @format A data frame with one column:
#' \describe{
#'	\item{`types`}{`character` The types of Pokemon. Possible types include `Grass`, `Fire`, `Water`, `Bug`, `Normal`, `Dark`, `Poison`, `Electric`, `Ground`, `Ice`, `Fairy`, `Steel`, `Fighting`, `Psychic`, `Rock`, `Ghost`, `Dragon`, `Flying`.}
#' }
#' @source [Bulbapedia Type](https://bulbapedia.bulbagarden.net/wiki/Type)
#'
#'
#'
#' @examples
#' data(types)
"types"
#' Pokémon Type Effectiveness Dataset
#'
#' This dataset provides a matrix of effectiveness multipliers for different types of Pokémon attacks.
#' Each Pokémon has a type, such as Fire, Water, Grass, etc., and each type has different effectiveness against other types.
#' This effectiveness is represented by a multiplier that is applied to the attack's damage.
#' 
#' The dataset is structured as a wide format, with each column representing a defending Pokémon's type and
#' each row representing an attacking Pokémon's type.
#' @format A data frame with 19 variables (1 for the attacking type and 18 for each defending type):
#' \describe{
#'	\item{`Attacking`}{`factor` The type of the attacking Pokémon's move. There are 18 types in total.}
#'	\item{`Defending_Normal`}{`numeric` Effectiveness against Normal type.}
#'	\item{`Defending_Fighting`}{`numeric` Effectiveness against Fighting type.}
#'	\item{`Defending_Flying`}{`numeric` Effectiveness against Flying type.}
#'	\item{`Defending_Poison`}{`numeric` Effectiveness against Poison type.}
#'	\item{`Defending_Ground`}{`numeric` Effectiveness against Ground type.}
#'	\item{`Defending_Rock`}{`numeric` Effectiveness against Rock type.}
#'	\item{`Defending_Bug`}{`numeric` Effectiveness against Bug type.}
#'	\item{`Defending_Ghost`}{`numeric` Effectiveness against Ghost type.}
#'	\item{`Defending_Steel`}{`numeric` Effectiveness against Steel type.}
#'	\item{`Defending_Fire`}{`numeric` Effectiveness against Fire type.}
#'	\item{`Defending_Water`}{`numeric` Effectiveness against Water type.}
#'	\item{`Defending_Grass`}{`numeric` Effectiveness against Grass type.}
#'	\item{`Defending_Electric`}{`numeric` Effectiveness against Electric type.}
#'	\item{`Defending_Psychic`}{`numeric` Effectiveness against Psychic type.}
#'	\item{`Defending_Ice`}{`numeric` Effectiveness against Ice type.}
#'	\item{`Defending_Dragon`}{`numeric` Effectiveness against Dragon type.}
#'	\item{`Defending_Dark`}{`numeric` Effectiveness against Dark type.}
#'	\item{`Defending_Fairy`}{`numeric` Effectiveness against Fairy type.}
#' }
#' @source [Bulbapedia Type](https://bulbapedia.bulbagarden.net/wiki/Type)
#'
#'
#'
#' @examples
#' data(typeChartWide)
"typeChartWide"
#' Extended Pokémon Type Effectiveness Dataset
#'
#' This dataset provides detailed effectiveness values for attacks between different Pokémon types.
#' 
#' It is structured in a long format, with each row representing an interaction between an attacking type and a defending type.
#' The 'Effectiveness' column provides the multiplier for the effectiveness of the attack.
#' @format A data frame with 3 variables:
#' \describe{
#'	\item{`Attacking`}{`factor` The type of the attacking Pokémon's move. There are 18 types in total.}
#'	\item{`Defending`}{`factor` The type of the defending Pokémon. There are 18 types in total.}
#'	\item{`Effectiveness`}{`numeric` The multiplier for the effectiveness of the attack. It lists the effectiveness of an attacking type against a defending type, with numerical values indicating the level of effectiveness: 0 denotes immunity (no effect), 0.5 means the attack is not very effective (half damage), 1 means the attack is effective (regular damage), and 2 means the attack is very effective (double damage).}
#' }
#' @source [Bulbapedia Type](https://bulbapedia.bulbagarden.net/wiki/Type)
#'
#'
#'
#' @examples
#' data(typeChart)
"typeChart"
#' Pokemon Weight Dataset
#'
#' This dataset contains information about the weight of various Pokémon.
#' Each Pokémon's weight is recorded in both pounds (lbs) and kilograms (kg), providing flexibility for different uses.
#' The dataset also includes details about the lightest and heaviest Pokémon, their regional forms, and whether they have a Mega or Primal form.
#' This can be useful for a variety of analyses, such as studying the distribution of Pokémon weights,
#' identifying trends and patterns, or informing game strategies.
#' @format A data frame with 8 variables:
#' \describe{
#'	\item{`name`}{`character` The name of the Pokémon.}
#'	\item{`form`}{`character` The form of the Pokémon. This refers to the different physical forms that Pokémon can take. 'NA' if the Pokémon does not have another form.}
#'	\item{`lbs`}{`numeric` The weight of the Pokémon in pounds.}
#'	\item{`kg`}{`numeric` The weight of the Pokémon in kilograms.}
#'	\item{`lightest`}{`integer` The rank of the Pokémon from lightest (1) to heaviest (1181).}
#'	\item{`heaveiest`}{`integer` The rank of the Pokémon from heaviest (1) to lightest (1181).}
#'	\item{`regional`}{`character` The regional form of the Pokémon. This refers to the variations of Pokémon that appear differently and have different attributes compared to their counterparts in other regions. 'NA' if the Pokémon does not have a regional form.}
#'	\item{`MegaOrPrimal`}{`character` Indicates if the Pokémon is in a Mega or Primal form. These are special forms that certain Pokémon can take.}
#' }
#' @source [Bulbapedia Weight](https://bulbapedia.bulbagarden.net/wiki/List_of_Pok%C3%A9mon_by_weight)
#'
#'
#'
#' @examples
#' data(weight)
"weight"
#' Height Dataset
#'
#' This dataset contains information about the height of different Pokémon forms.
#' The height is represented in different units such as feet (ft), meters (m), and inches (inch),
#' providing flexibility for different uses.
#' It also includes the ranking of each Pokémon form from smallest to biggest, and information about regional forms and Mega or Primal forms.
#' This can be useful for a variety of analyses, such as studying the distribution of Pokémon heights,
#' identifying trends and patterns, or informing game strategies.
#' @format A data frame with 8 variables:
#' \describe{
#'	\item{`name`}{`character` The name of the Pokémon.}
#'	\item{`form`}{`character` The specific form of the Pokémon. This refers to the different physical forms that Pokémon can take.}
#'	\item{`ft`}{`numeric` The height of the Pokémon in feet.}
#'	\item{`m`}{`numeric` The height of the Pokémon in meters.}
#'	\item{`inch`}{`numeric` The height of the Pokémon in inches.}
#'	\item{`smallest`}{`integer` The ranking of the Pokémon from smallest to biggest.}
#'	\item{`bigest`}{`integer` The ranking of the Pokémon from biggest to smallest.}
#'	\item{`regional`}{`character` The regional form of the Pokémon. This refers to the variations of Pokémon that appear differently and have different attributes compared to their counterparts in other regions.}
#'	\item{`MegaOrPrimal`}{`character` Indicates if the Pokémon is in a Mega or Primal form. These are special forms that certain Pokémon can take.}
#' }
#' @source [Bulbapedia Height](https://bulbapedia.bulbagarden.net/wiki/List_of_Pok%C3%A9mon_by_height)
#'
#'
#'
#' @examples
#' data(height)
"height"
#' Physical Attributes of Pokémon
#'
#' This dataset provides a comprehensive overview of the physical attributes of Pokémon, including their type,
#' generation, weight, height, and other characteristics.
#' It includes information about each Pokémon's National Pokédex number, name, regional variant,
#' primary and secondary types, generation, legendary status, mythical status, ultra beast status,
#' family, size, form, weight in pounds and kilograms, lightest and heaviest weight rankings in the Pokédex,
#' Mega or Primal form status, height in feet, meters, and inches, and smallest and
#' biggest height rankings in the Pokédex.
#' 
#' This dataset can be useful for a variety of analyses, such as studying the distribution of Pokémon
#' weights and heights, identifying trends and patterns, or informing game strategies.
#' @format A data frame with 22 variables:
#' \describe{
#'	\item{`ndex`}{`integer` The National Pokédex number of the Pokémon. This is the official numbering scheme that is used in every Pokémon game and media.}
#'	\item{`name`}{`character` The name of the Pokémon. This is the common name used to identify a particular Pokémon.}
#'	\item{`regional`}{`character` The regional variant of the Pokémon, if any. This refers to the variations of Pokémon that appear differently and have different attributes compared to their counterparts in other regions.}
#'	\item{`type`}{`character` The primary type of the Pokémon. Each Pokémon has a primary type which determines the Pokémon's strengths and weaknesses.}
#'	\item{`type2`}{`character` The secondary type of the Pokémon, if any. Some Pokémon may have a secondary type, which further influences the Pokémon's strengths and weaknesses.}
#'	\item{`generation`}{`integer` The generation of the Pokémon. This refers to the generation of games in which the Pokémon was first introduced.}
#'	\item{`isLegendary`}{`logical` A boolean indicating if the Pokémon is Legendary. Legendary Pokémon are a group of incredibly rare and often very powerful Pokémon.}
#'	\item{`isMythical`}{`logical` A boolean indicating if the Pokémon is Mythical. Mythical Pokémon are a related but separate group of Pokémon, which are usually event-exclusive.}
#'	\item{`isUltraBeast`}{`logical` A boolean indicating if the Pokémon is an Ultra Beast. Ultra Beasts is a term introduced in Generation VII to classify seven known Pokémon.}
#'	\item{`family`}{`character` The family of the Pokémon. This refers to the group or lineage the Pokémon belongs to, often based on common themes or characteristics among the Pokémon.}
#'	\item{`size`}{`character` The size of the Pokémon. This refers to the height and weight of the Pokémon.}
#'	\item{`form`}{`character` The form of the Pokémon. This refers to the different physical forms that Pokémon can take.}
#'	\item{`lbs`}{`numeric` The weight of the Pokémon in pounds.}
#'	\item{`kg`}{`numeric` The weight of the Pokémon in kilograms.}
#'	\item{`lightest`}{`integer` The rank of the Pokémon from lightest (1) to heaviest (1181).}
#'	\item{`heaveiest`}{`integer` The rank of the Pokémon from heaviest (1) to lightest (1181).}
#'	\item{`MegaOrPrimal`}{`character` Indicates if the Pokémon is in a Mega or Primal form. These are special forms that certain Pokémon can take.}
#'	\item{`ft`}{`character` The height of the Pokémon in feet.}
#'	\item{`m`}{`numeric` The height of the Pokémon in meters.}
#'	\item{`inch`}{`integer` The height of the Pokémon in inches.}
#'	\item{`smallest`}{`integer` The ranking of the Pokémon from smallest to biggest.}
#'	\item{`bigest`}{`integer` The ranking of the Pokémon from biggest to smallest.}
#' }
#' @source [Bulbapedia Weight](https://bulbapedia.bulbagarden.net/wiki/List_of_Pok%C3%A9mon_by_weight)
#' [Bulbapedia Height](https://bulbapedia.bulbagarden.net/wiki/List_of_Pok%C3%A9mon_by_height)
#'
#'
#'
#' @examples
#' data(physicalAttr)
"physicalAttr"
#' Catch Rate Dataset
#'
#' This dataset provides information about the catch rate of each Pokémon.
#' The catch rate is a statistic that determines the probability of capturing a Pokémon.
#' A higher catch rate means that the Pokémon is easier to catch.
#' 
#' In the context of Pokémon Legends: Arceus, many Pokémon were given heightened catch rates to facilitate catching them
#' outside of battle.
#' @format A data frame with 5 variables:
#' \describe{
#'	\item{`ndex`}{`integer` The National Pokédex number of the Pokémon. This is the unique identifier for each Pokémon in the National Pokédex.}
#'	\item{`name`}{`character` The name of the Pokémon. This is the common name used to identify a particular Pokémon.}
#'	\item{`catchRate`}{`integer` The catch rate of the Pokémon. This is a value that represents the probability of capturing the Pokémon. Higher values indicate a higher probability of capture.}
#'	\item{`note`}{`character` Additional notes about the catch rate of the Pokémon. This may include information about specific conditions or factors that can influence the catch rate.}
#'	\item{`hdex`}{`integer` The Pokémon Legends: Arceus Pokédex number. This is the unique identifier for each Pokémon in the Pokémon Legends: Arceus Pokédex.}
#' }
#' @source [Bulbapedia Catch Rate](https://bulbapedia.bulbagarden.net/wiki/List_of_Pok%C3%A9mon_by_catch_rate)
#'
#'
#'
#' @examples
#' data(catchRate)
"catchRate"
#' Pokémon Mega Evolution and Primal Reversion
#'
#' This dataset contains information about Pokémon that can undergo Mega Evolution and Primal Reversion,
#' which are special forms of evolution that Pokémon can undergo during battle to become more powerful.
#' These Pokémon are categorized by their National Pokédex number, name, type before and after evolution, ability before and after evolution, and the stone required for the evolution.
#' 
#' For example, ‘Rayquaza’ is a Dragon/Flying type Pokémon with the ability ‘Air Lock’ that can undergo
#' Mega Evolution to remain a Dragon/Flying type but with the ability ‘Delta Stream’. Unlike other Pokémon,
#' Rayquaza does not require a Mega Stone to undergo Mega Evolution. Instead, Rayquaza must swallow the
#' Meteorite and learn Dragon Ascent during the Delta Episode or must be taught Dragon Ascent via move tutor.
#' 
#' The 'Primal Reversion' refers to Kyogre and Groudon,
#' which are ancient Pokémon that revert to their primal forms with the Blue Orb and Red Orb respectively,
#' changing their abilities to 'Primordial Sea' and 'Desolate Land'.
#' 
#' Note that there exist Primal Dialga, hovever this appears to be different from Primal Reversion.
#' @format A data frame with 9 variables:
#' \describe{
#'	\item{`ndex`}{`integer` The National Pokédex number of the Pokémon.}
#'	\item{`name`}{`character` The name of the Pokémon.}
#'	\item{`typeBefore`}{`character` The primary type of the Pokémon before Mega Evolution or Primal Reversion.}
#'	\item{`type2Before`}{`character` The secondary type of the Pokémon before Mega Evolution or Primal Reversion, if applicable.}
#'	\item{`abilityBefore`}{`character` The ability of the Pokémon before Mega Evolution or Primal Reversion.}
#'	\item{`typeAfter`}{`character` The primary type of the Pokémon after Mega Evolution or Primal Reversion.}
#'	\item{`type2After`}{`character` The secondary type of the Pokémon after Mega Evolution or Primal Reversion, if applicable.}
#'	\item{`abilityAfter`}{`character` The ability of the Pokémon after Mega Evolution or Primal Reversion.}
#'	\item{`stone`}{`character` The Mega Stone or Orb required for the Pokémon to undergo Mega Evolution or Primal Reversion.  Or a note in case of Rayquaza}
#' }
#' @source [Mega Evolution. In Bulbapedia.](https://bulbapedia.bulbagarden.net/wiki/Mega_Evolution)
#' [Primal Reversion. In Bulbapedia.](https://bulbapedia.bulbagarden.net/wiki/Primal_Reversion)
#'
#'
#'
#' @examples
#' data(mega)
"mega"
