name: Update Wiki
on:
  push:
    paths:
      - 'wiki/**'
    branches:
      - main

permissions:
  contents: write

jobs:
  update-wiki:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Push changes to Wiki
        uses: OrlovM/Wiki-Action@v1
        with:
          path: 'wiki'
          token: ${{ secrets.GITHUB_TOKEN }}
